/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param title 
 * @param coverImage 
 * @param metascore 
 * @param releaseDate 
 * @param platforms 
 * @param genres 
 */


data class GameSummary (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("coverImage")
    val coverImage: kotlin.String? = null,

    @SerializedName("metascore")
    val metascore: kotlin.Int? = null,

    @SerializedName("releaseDate")
    val releaseDate: kotlin.String? = null,

    @SerializedName("platforms")
    val platforms: kotlin.collections.Set<kotlin.String>? = null,

    @SerializedName("genres")
    val genres: kotlin.collections.Set<kotlin.String>? = null

) {


}

