/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param developer 
 * @param publisher 
 * @param releaseDate 
 * @param esrbRating 
 * @param metascore 
 * @param coverImage 
 * @param genreNames 
 * @param platformNames 
 */


data class GameDetail (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("developer")
    val developer: kotlin.String? = null,

    @SerializedName("publisher")
    val publisher: kotlin.String? = null,

    @SerializedName("releaseDate")
    val releaseDate: kotlin.String? = null,

    @SerializedName("esrbRating")
    val esrbRating: kotlin.String? = null,

    @SerializedName("metascore")
    val metascore: kotlin.Int? = null,

    @SerializedName("coverImage")
    val coverImage: kotlin.String? = null,

    @SerializedName("genreNames")
    val genreNames: kotlin.collections.Set<kotlin.String>? = null,

    @SerializedName("platformNames")
    val platformNames: kotlin.collections.Set<kotlin.String>? = null,

    @SerializedName("genres")
    val genres: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("platforms")
    val platforms: kotlin.collections.List<kotlin.String>? = null
) {


}

