/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model

import com.gamejoint.app.data.model.Pageablenull
import com.gamejoint.app.data.model.ReviewResponse
import com.gamejoint.app.data.model.Sortnull

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param totalElements 
 * @param totalPages 
 * @param propertySize 
 * @param content 
 * @param number 
 * @param pageable 
 * @param sort 
 * @param first 
 * @param last 
 * @param numberOfElements 
 * @param empty 
 */


data class PageReviewResponse (

    @SerializedName("totalElements")
    val totalElements: kotlin.Long? = null,

    @SerializedName("totalPages")
    val totalPages: kotlin.Int? = null,

    @SerializedName("size")
    val propertySize: kotlin.Int? = null,

    @SerializedName("content")
    val content: kotlin.collections.List<ReviewResponse>? = null,

    @SerializedName("number")
    val number: kotlin.Int? = null,

    @SerializedName("pageable")
    val pageable: Pageablenull? = null,

    @SerializedName("sort")
    val sort: Sortnull? = null,

    @SerializedName("first")
    val first: kotlin.Boolean? = null,

    @SerializedName("last")
    val last: kotlin.Boolean? = null,

    @SerializedName("numberOfElements")
    val numberOfElements: kotlin.Int? = null,

    @SerializedName("empty")
    val empty: kotlin.Boolean? = null

) {


}

