/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model

import com.gamejoint.app.data.model.Sortnull

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param offset 
 * @param pageNumber 
 * @param pageSize 
 * @param paged 
 * @param sort 
 * @param unpaged 
 */


data class Pageablenull (

    @SerializedName("offset")
    val offset: kotlin.Long? = null,

    @SerializedName("pageNumber")
    val pageNumber: kotlin.Int? = null,

    @SerializedName("pageSize")
    val pageSize: kotlin.Int? = null,

    @SerializedName("paged")
    val paged: kotlin.Boolean? = null,

    @SerializedName("sort")
    val sort: Sortnull? = null,

    @SerializedName("unpaged")
    val unpaged: kotlin.Boolean? = null

) {


}

