/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param otpCode The 6-digit code sent to the user's email
 * @param newPassword The newly chosen password
 */
data class PasswordChangeRequest (

    @SerializedName("otpCode")
    val otpCode: kotlin.String? = null,

    @SerializedName("newPassword")
    val newPassword: kotlin.String? = null

)