/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param authorUsername 
 * @param authorRole 
 * @param score 
 * @param comment 
 * @param createdAt 
 * @param status 
 */


data class ReviewResponse (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("authorUsername")
    val authorUsername: kotlin.String? = null,

    @SerializedName("authorRole")
    val authorRole: kotlin.String? = null,

    @SerializedName("score")
    val score: kotlin.Int? = null,

    @SerializedName("comment")
    val comment: kotlin.String? = null,

    @SerializedName("createdAt")
    val createdAt: kotlin.String? = null,

    @SerializedName("status")
    val status: kotlin.String? = null

) {


}

