/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param gameId 
 * @param score 
 * @param comment 
 */


data class ReviewCreateRequest (

    @SerializedName("gameId")
    val gameId: kotlin.Long? = null,

    @SerializedName("score")
    val score: kotlin.Int? = null,

    @SerializedName("comment")
    val comment: kotlin.String? = null

) {


}

