/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param empty 
 * @param sorted 
 * @param unsorted 
 */


data class Sortnull (

    @SerializedName("empty")
    val empty: kotlin.Boolean? = null,

    @SerializedName("sorted")
    val sorted: kotlin.Boolean? = null,

    @SerializedName("unsorted")
    val unsorted: kotlin.Boolean? = null

) {


}

