/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param username 
 * @param email 
 * @param dob 
 * @param isVerified 
 * @param createdAt 
 * @param roleName 
 * @param isBanned 
 * @param banExpiresAt 
 */


data class UserProfileResponse (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("dob")
    val dob: java.time.LocalDate? = null,

    @SerializedName("isVerified")
    val isVerified: kotlin.Boolean? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerializedName("roleName")
    val roleName: kotlin.String? = null,

    @SerializedName("isBanned")
    val isBanned: kotlin.Boolean? = null,

    @SerializedName("banExpiresAt")
    val banExpiresAt: java.time.OffsetDateTime? = null

) {


}

