/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param usernameOrEmail 
 * @param password 
 * @param rememberMe 
 * @param cfTurnstileResponse 
 */


data class UserLoginRequest (

    @SerializedName("usernameOrEmail")
    val usernameOrEmail: kotlin.String? = null,

    @SerializedName("password")
    val password: kotlin.String? = null,

    @SerializedName("rememberMe")
    val rememberMe: kotlin.Boolean? = null,

    @SerializedName("cfTurnstileResponse")
    val cfTurnstileResponse: kotlin.String? = null

) {


}

