/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gamejoint.app.data.model

import com.google.gson.annotations.SerializedName
import java.time.LocalDate
import java.time.LocalDateTime

data class UserProfileResponse (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("dob")
    val dob: LocalDate? = null,

    @SerializedName("isVerified")
    val isVerified: kotlin.Boolean? = null,

    // FIXED: Changed from OffsetDateTime to LocalDateTime to match Spring Boot
    @SerializedName("createdAt")
    val createdAt: LocalDateTime? = null,

    @SerializedName("roleName")
    val roleName: kotlin.String? = null,

    @SerializedName("isBanned")
    val isBanned: kotlin.Boolean? = null,

    // FIXED: Changed from OffsetDateTime to LocalDateTime
    @SerializedName("banExpiresAt")
    val banExpiresAt: LocalDateTime? = null,

    // FIXED: Changed from OffsetDateTime to LocalDateTime
    @SerializedName("deletionDate")
    val deletionDate: LocalDateTime? = null

)